server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/v1/students/**

        - id: school-service
          uri: lb://school-service
          predicates:
            - Path=/api/v1/schools/**