server:
  port: 8091

spring:
  datasource:
    url: ${SCHOOL_DB_URL}
    username: ${SCHOOL_DB_USER}
    password: ${SCHOOL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: app
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/master-changelog.yaml
    default-schema: app
    liquibase-schema: liquibase

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: school-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "student:com.educore.schoolservice.event.StudentCreatedEvent"

logging:
  level:
    root: INFO
    com.educore: INFO