server:
  port: 8090

spring:
  datasource:
    url: ${STUDENT_DB_URL}
    username: ${STUDENT_DB_USER}
    password: ${STUDENT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: app
        format_sql: true
        show_sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/master-changelog.yaml
    default-schema: app
    liquibase-schema: liquibase

logging:
  level:
    root: INFO